# Generated by Django 5.2.12 on 2026-03-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img_author',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
